[GLOBAL]
pants_version = "2.8.0"
print_stacktrace = true
pythonpath = ["pants-plugins"]

backend_packages = [
    "pants.backend.python",
    "experimental.pyoxidizer",
]

[source]
root_patterns = [
    "pants-plugins",
    "helloworld", 
]

[python]
interpreter_constraints = [">=3.9"]

[anonymous-telemetry]
enabled = false
