[GLOBAL]
pants_version = "2.8.0"
pantsd = true 
print_stacktrace = true
pythonpath = ["pants-plugins"]

backend_packages = [
    "pants.backend.python",
    "experimental.pyoxidizer",
]

[source]
root_patterns = [
    "pants-plugins",
    "helloworld", 
    "hellofastapi", 
]

[python]
interpreter_constraints = [">=3.9"]
requirement_constraints = "requirements.constraints.txt"

[anonymous-telemetry]
enabled = false
